/**
 * Infrastructure-as-code skeletons generated from the design graph.
 *
 * The output is a starting point, not a deployable stack: every resource is
 * emitted with its correct provider type and a `depends_on` derived from the
 * design's edges, and the attributes an engineer must fill in are marked
 * `TODO`. Emitting invented attribute values would be worse than emitting
 * none — a reviewer can trust that nothing here is fabricated.
 */

import { getEntry } from './catalog.js';
import { upstream } from './graph.js';

/** `EC2 (Web)` -> `ec2_web`; guaranteed non-empty and unique within a design. */
export function terraformName(name, taken = new Set()) {
  let base = String(name).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  if (!base) base = 'resource';
  if (/^[0-9]/.test(base)) base = `r_${base}`;
  let candidate = base;
  let i = 2;
  while (taken.has(candidate)) candidate = `${base}_${i++}`;
  taken.add(candidate);
  return candidate;
}

/** `EC2 (Web)` -> `Ec2Web`; CloudFormation logical ids must be alphanumeric. */
export function logicalId(name, taken = new Set()) {
  let base = String(name)
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
  if (!base) base = 'Resource';
  if (/^[0-9]/.test(base)) base = `R${base}`;
  let candidate = base;
  let i = 2;
  while (taken.has(candidate)) candidate = `${base}${i++}`;
  taken.add(candidate);
  return candidate;
}

/** Stable, human-readable names for every node: Terraform and CFN forms. */
function nameNodes(design) {
  const tf = new Set();
  const cfn = new Set();
  const out = new Map();
  for (const n of design.nodes) {
    out.set(n.id, { tf: terraformName(n.name, tf), cfn: logicalId(n.name, cfn) });
  }
  return out;
}

const TF_HEADER = `# Generated by Cloud Architecture Designer — a skeleton, not a deployable stack.
# Each resource is typed correctly and ordered by the design's edges; every
# attribute marked TODO must be completed and reviewed before \`terraform plan\`.

terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

variable "region" {
  type    = string
  default = "us-east-1"
}

provider "aws" {
  region = var.region
}
`;

/**
 * @param {import('./graph.js').Design} design
 * @returns {string} HCL
 */
export function toTerraform(design) {
  if (!design.nodes.length) return `${TF_HEADER}\n# (empty design)\n`;
  const names = nameNodes(design);
  const blocks = design.nodes.map((n) => {
    const entry = getEntry(n.type);
    const me = names.get(n.id);
    const deps = upstream(design, n.id)
      .map((id) => {
        const dep = design.nodes.find((d) => d.id === id);
        return dep ? `${getEntry(dep.type).terraform}.${names.get(id).tf}` : null;
      })
      .filter(Boolean);
    const lines = [
      `# ${n.name} (${entry.name})`,
      `resource "${entry.terraform}" "${me.tf}" {`,
      `  # TODO: required attributes for ${entry.terraform}`,
      `  tags = {`,
      `    Name      = "${n.name.replace(/"/g, '\\"')}"`,
      `    Category  = "${entry.category}"`,
      `    ManagedBy = "cloud-architecture-designer"`,
      `  }`
    ];
    if (deps.length) {
      lines.push(`  depends_on = [`);
      for (const d of deps) lines.push(`    ${d},`);
      lines.push(`  ]`);
    }
    lines.push(`}`);
    return lines.join('\n');
  });
  return `${TF_HEADER}\n${blocks.join('\n\n')}\n`;
}

/**
 * @param {import('./graph.js').Design} design
 * @returns {string} YAML
 */
export function toCloudFormation(design) {
  const head = [
    `AWSTemplateFormatVersion: '2010-09-09'`,
    `Description: >-`,
    `  Generated by Cloud Architecture Designer. A skeleton, not a deployable`,
    `  stack: complete every TODO before deploying.`,
    ``
  ];
  if (!design.nodes.length) return `${head.join('\n')}Resources: {}\n`;
  const names = nameNodes(design);
  const out = [...head, `Resources:`];
  for (const n of design.nodes) {
    const entry = getEntry(n.type);
    const me = names.get(n.id);
    const deps = upstream(design, n.id).map((id) => names.get(id)?.cfn).filter(Boolean);
    out.push(`  ${me.cfn}:`);
    out.push(`    Type: ${entry.cfn}`);
    if (deps.length) {
      out.push(`    DependsOn:`);
      for (const d of deps) out.push(`      - ${d}`);
    }
    out.push(`    Properties: {}  # TODO: required properties for ${entry.cfn}`);
    out.push(`    Metadata:`);
    out.push(`      Designer:`);
    out.push(`        Name: ${yamlString(n.name)}`);
    out.push(`        Category: ${entry.category}`);
  }
  return `${out.join('\n')}\n`;
}

/** Quote a YAML scalar safely. */
function yamlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** Markdown summary of a review, suitable for pasting into a design doc. */
export function toReviewMarkdown(design, review, cost) {
  const lines = [
    `# Well-Architected review`,
    ``,
    `- Components: ${design.nodes.length}`,
    `- Connections: ${design.edges.length}`,
    `- Illustrative monthly planning figure: $${Math.round(cost.total).toLocaleString('en-US')} (placeholders, not list prices)`,
    `- Score: ${review.score === null ? 'n/a' : `${review.score} / 100`} across ${review.findings.filter((f) => f.status !== 'na').length} applicable checks`,
    ``,
    `| Rule | Pillar | Check | Status | Note |`,
    `| --- | --- | --- | --- | --- |`
  ];
  for (const f of review.findings) {
    lines.push(`| ${f.id} | ${f.pillarLabel} | ${f.title} | ${f.status} | ${f.note.replace(/\|/g, '\\|')} |`);
  }
  return `${lines.join('\n')}\n`;
}
